Feature one
Teaching-projects/SOE-SZTA-2021-KEKW pull request #3
Opened 2021-02-22 11:41 UTC by gregkiss98

2021-02-22 12:09 UTC, hegyhati requested changes
Egy aprosag.

2021-02-22 12:09 UTC, hegyhati commented on main.java
>          battle(Knight1, Knight2);
Nem az uj reszben van, de a battle-ben  a Knight2 akkor is visszaut, ha mar meghalt.

2021-03-05 08:27 UTC, gregkiss98 commented
@hegyhati Javítottuk a hibát.

2021-03-05 16:19 UTC, hegyhati approved these changes

2021-03-05 16:20 UTC, merged