F3/2 feladat elkészítése
Teaching-projects/SOE-SZTA-2021-KEKW pull request #4
Opened 2021-03-06 20:44 UTC by gregkiss98

A lovag akkor képes támadni, amikor páros számot kap a generátorból.
@hegyhati Megnézed légyszíves?

2021-03-07 22:52 UTC, hegyhati commented
Az a sejtesem, hogy teljesen felreertettetek a feladatot. 

Tfh K1 attackspeedje 2.3, K2-e pedig 5.

Akkor:
2.3-kor K1 meguti K2-t
4.6-kor K1 meguti K2-t
5-kor K2 meguti K1-et
6.9-kor K1 meguti K2-t
...


Igy mar vilagos?

2021-03-08 11:20 UTC, gregkiss98 commented
@hegyhati Javítottam, azt hiszem most jó. A megoldás nem teljesen ugyan az mint amit te írtál, de a logika szerintem igen.

2021-03-09 01:46 UTC, hegyhati requested changes
A lenyege most mar jo, viszont ez csak int attackspeedeket fogad el, es a peldaban nem veletlen volt double. Mukodnie kell arra is.

2021-03-10 09:12 UTC, gregkiss98 commented
@hegyhati Kész a feladat.

2021-03-10 12:33 UTC, hegyhati requested changes

2021-03-10 12:33 UTC, hegyhati commented on main.java
> +            szamlalo = round(szamlalo, 2);
es mi van, ha valakinek az attack speedje 0.004? Nem volt semmi ilyen megkotesem. 

A masik, hogy ez egy nagyon lassu algoritmus, ha mondjuk az attackspeed 100 es 200, akkor 1000 iteraciot kell varni, hogy usson az elso.

2021-03-10 12:33 UTC, hegyhati commented on Unit.java
> +    double hp;
ezek maradjanak nyugodtan int-ek, it tnem lenne celszeru kerekitesi dolgokkal foglalkozni.

2021-03-10 20:20 UTC, gregkiss98 commented
@hegyhati Kérnék egy megtekintést, légyszíves!

2021-03-12 11:14 UTC, hegyhati requested changes
Ket aprosag.

2021-03-12 11:14 UTC, hegyhati commented on main.java
>                  Knight2.attack(Knight1);
Ha mar meghalt, ne usson vissza.

2021-03-12 11:14 UTC, hegyhati commented on main.java
> +                Knight1.setAs(defAsKN1);
Namost ha nem a csata metodus, hanem maga az object maintaineli, hogy Neki hogy all a cooldown-ja, akkor ne kelljen neki megadni, hogy mennyire allitsa, amikor a "default"-ra visszaallitja. Azt mar jegyezze O meg. Ez itt logikailag igy azert bubis, mert ha mondjuk valamiert nem a "defaulton" volt ez a cooldown, akkor utana mindig a csata elejen levore teszi vissza, nem arra, amire kellene. (nem tudom, ertheto-e amit irtam)

2021-03-12 17:35 UTC, gregkiss98 commented
@hegyhati Erre gondoltál?

2021-03-17 10:48 UTC, hegyhati approved these changes

2021-03-17 10:48 UTC, merged